---
- name: Install hugo package
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Create /tmp/hugo-download
      file:
        path: /tmp/hugo-download
        state: directory

    - name: Download Hugo package
      get_url:
        url: https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_extended_0.101.0_Linux-64bit.tar.gz
        dest: /tmp/hugo-download/hugo.tar.gz
        mode: 0777

    - name: Unpack Hugo Package
      unarchive:
        src: /tmp/hugo-download/hugo.tar.gz
        dest: /usr/local/bin
        
